// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"dove/internal/app"
	"dove/internal/handler"
	"dove/internal/repository"
	"dove/internal/service"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp() (*app.App, error) {
	engine := ProvideGinEngine()
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	authHandler := handler.NewAuthHandler(userService)
	healthHandler := handler.NewHealthHandler()
	userHandler := handler.NewUserHandler(userService)
	weaponRepository := repository.NewWeaponRepository()
	weaponService := service.NewWeaponService(weaponRepository)
	weaponHandler := handler.NewWeaponHandler(weaponService)
	timezoneHandler := handler.NewTimezoneHandler()
	troveRepository := repository.NewTroveRepository()
	troveService := service.NewTroveService(troveRepository)
	troveHandler := handler.NewTroveHandler(troveService)
	appApp := app.NewApp(engine, authHandler, healthHandler, userHandler, weaponHandler, timezoneHandler, troveHandler)
	return appApp, nil
}
