// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/deantook/dove/internal/config"
	"github.com/deantook/dove/internal/handler"
	"github.com/deantook/dove/internal/repository"
	"github.com/deantook/dove/internal/router"
	"github.com/deantook/dove/internal/service"
	"github.com/deantook/dove/pkg/database"
	"github.com/deantook/dove/pkg/redis"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	redis2 "github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeServer 初始化服务器
func InitializeServer(cfg *config.Config) (*gin.Engine, error) {
	databaseConfig := &cfg.Database
	db, err := database.Init(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	redisConfig := &cfg.Redis
	client, err := redis.Init(redisConfig)
	if err != nil {
		return nil, err
	}
	userService := service.NewUserService(userRepository, client)
	userHandler := handler.NewUserHandler(userService)
	routerRouter := router.NewRouter(userHandler)
	engine := routerProvider(routerRouter)
	return engine, nil
}

// wire.go:

// routerProvider 提供 Router 的 Engine
func routerProvider(r *router.Router) *gin.Engine {
	r.SetupRoutes()
	return r.GetEngine()
}

// ProviderSet 提供者集合
var ProviderSet = wire.NewSet(database.Init, redis.Init, repository.NewUserRepository, service.NewUserService, handler.NewUserHandler, router.NewRouter)

// 显式声明依赖关系
var (
	_ *gorm.DB
	_ *redis2.Client
	_ repository.UserRepository
	_ service.UserService
	_ *handler.UserHandler
	_ *router.Router
)
